version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_dima_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - .:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

